### ISSUE TITLE
Implement option to let user select number of features to select

### ISSUE THREAD

**Issue by raamana** [raamana/neuropredict#6]
To do:
- [x] add an argument: --num_features
- [x] describe the argument thoroughly in help text
- [x] checks on the input types
- [x] checks on the input ranges
- [ ] checks on whether all the feature sets have the same number of features
- [ ] make the new argument interface with all the other methods, if need be.
- [ ] add option to pass on subset of feature names to visualize.feature_importance_map

We can add/remove as we realize them.

**Comment by amandakeasson** [comment]
looking forward to working on this! :)

**Comment by amandakeasson** [comment]
Hi Pradeep!

I added the new argument, but I called it "nfeatures" because there is already a "num_features" variable in one of the functions that is defined in rhst.py.

Also, I changed the dtype in the metadata import command to "str" - this prevented the issue I was experiencing earlier when the subject list wasn't imported properly.

**Comment by raamana** [comment]
Awsome! Can you check off the above to do list for the implementation and modify as necessary? 

Before you make a pull request, I'd try testing it offline:
- [ ] with break points and print statements
- [ ] couple of runs with different values for actual data

**Comment by amandakeasson** [comment]
For sure! I'll copy the list here and edit this post because I'm not able to edit your initial post. 

To do:

- [X]  add an argument: --num_features
- [X]  describe the argument thoroughly in help text
- [X]  checks on the input types
- [X]  checks on the input ranges
- [ ]  checks on whether all the feature sets have the same number of features
- [ ]  make the new argument interface with all the other methods, if need be.
- [ ]  add option to pass on subset of feature names to visualize.feature_importance_map

**Comment by raamana** [comment]
You don't need to edit the post, just need to tick the items off. I can tick off your todo list, hope you can do that with mine.

**Comment by amandakeasson** [comment]
Unfortunately I'm not able to edit it, but I think this might work:

- from https://github.com/raamana/neuropredict: Settings --> Collaborators --> search for amandakeasson
- from https://github.com/raamana/neuropredict/issues: click the checkbox to the left of the issue --> click "assign" --> hopefully my name appears and I'll be able to use your checklist :)

**Comment by raamana** [comment]
Again, you don't need to edit it. Just mouse click on the radio button! Literally just click on it without editing it. This is not a big deal, just a way to track.

**Comment by amandakeasson** [comment]
Sorry, that's what I meant- that I'm not able to check off the boxes. I can check off the boxes on the checklist I copied into a new comment (i.e. without editing the post), but unfortunately I can't do the same for your checklist. Sorry for the confusion.

**Comment by raamana** [comment]
Not a big deal at all. I added you as a collaborator now, may be that should help. Either way this is no big deal :)

**Comment by amandakeasson** [comment]
It works now! Thanks :)

**Comment by raamana** [comment]
Hey Amanda, did you get time to work on this at all? I totally understand if you haven't been able to. Also, internal design changed a bit (actually a lot) when I tried to parallelize CV loop. Perhaps you can start from the new parallel version? Also I got some go at it for my use - you can use that? Let me know.

**Comment by raamana** [comment]
I guess you’re probably too busy with research and haven’t gotten to github in awhile. I’ll close this for now. Reopen it when you have time to work on this. Thanks a lot for your help so far.

**Comment by amandakeasson** [comment]
Will do!
